export default {
  baseball: {
    icon: require("../assets/images/icons/icon_baseball.png"),
    id: 2,
    type: "baseball",
    image: require("../assets/images/figures/baseball.png"),
    name: "Baseball",
  },
  basketball: {
    icon: require("../assets/images/icons/icon_basketball.png"),
    id: 0,
    type: "basketball",
    image: require("../assets/images/figures/basketball.png"),
    name: "Basketball",
  },
  bicycle: {
    icon: require("../assets/images/icons/icon_bicycle.png"),
    id: 3,
    type: "bicycle",
    image: require("../assets/images/figures/bicycle.png"),
    name: "Biking",
  },
  boardgame: {
    icon: require("../assets/images/icons/icon_boardgame.png"),
    id: 24,
    type: "boardgame",
    image: require("../assets/images/figures/boardgame.png"),
    name: "Games",
  },
  boxing: {
    icon: require("../assets/images/icons/icon_boxing.png"),
    id: 4,
    type: "boxing",
    image: require("../assets/images/figures/boxing.png"),
    name: "Boxing",
  },
  camping: {
    icon: require("../assets/images/icons/icon_camping.png"),
    id: 28,
    type: "camping",
    image: require("../assets/images/figures/camping.png"),
    name: "Camping",
  },
  climbing: {
    icon: require("../assets/images/icons/icon_climbing.png"),
    id: 5,
    type: "climbing",
    image: require("../assets/images/figures/climbing.png"),
    name: "Climbing",
  },
  dancing: {
    icon: require("../assets/images/icons/icon_dancing.png"),
    id: 6,
    type: "dancing",
    image: require("../assets/images/figures/dancing.png"),
    name: "Dancing",
  },
  football: {
    icon: require("../assets/images/icons/icon_football.png"),
    id: 7,
    type: "football",
    image: require("../assets/images/figures/football.png"),
    name: "Football",
  },
  frisbee: {
    icon: require("../assets/images/icons/icon_frisbee.png"),
    id: 27,
    type: "frisbee",
    image: require("../assets/images/figures/frisbee.png"),
    name: "Frisbee",
  },
  golf: {
    icon: require("../assets/images/icons/icon_golf.png"),
    id: 8,
    type: "golf",
    image: require("../assets/images/figures/golf.png"),
    name: "Golf",
  },
  hiking: {
    icon: require("../assets/images/icons/icon_hiking.png"),
    id: 9,
    type: "hiking",
    image: require("../assets/images/figures/hiking.png"),
    name: "Hiking",
  },
  hockey: {
    icon: require("../assets/images/icons/icon_hockey.png"),
    id: 10,
    type: "hockey",
    image: require("../assets/images/figures/hockey.png"),
    name: "Hockey",
  },
  kickball: {
    icon: require("../assets/images/icons/icon_kickball.png"),
    id: 11,
    type: "kickball",
    image: require("../assets/images/figures/kickball.png"),
    name: "Kickball",
  },
  pingpong: {
    icon: require("../assets/images/icons/icon_pingpong.png"),
    id: 12,
    type: "pingpong",
    image: require("../assets/images/figures/pingpong.png"),
    name: "Ping Pong",
  },
  running: {
    icon: require("../assets/images/icons/icon_running.png"),
    id: 13,
    type: "running",
    image: require("../assets/images/figures/running.png"),
    name: "Run/Walk",
  },
  soccer: {
    icon: require("../assets/images/icons/icon_soccer.png"),
    id: 14,
    type: "soccer",
    image: require("../assets/images/figures/soccer.png"),
    name: "Soccer",
  },
  softball: {
    icon: require("../assets/images/icons/icon_softball.png"),
    id: 15,
    type: "softball",
    image: require("../assets/images/figures/softball.png"),
    name: "Softball",
  },
  tennis: {
    icon: require("../assets/images/icons/icon_tennis.png"),
    id: 16,
    type: "tennis",
    image: require("../assets/images/figures/tennis.png"),
    name: "Tennis",
  },
  music: {
    icon: require("../assets/images/icons/icon_music.png"),
    id: 20,
    type: "music",
    image: require("../assets/images/figures/music.png"),
    name: "Music",
  },
  smoothie: {
    icon: require("../assets/images/icons/icon_smoothie.png"),
    id: 21,
    type: "smoothie",
    image: require("../assets/images/figures/smoothie.png"),
    name: "Smoothie",
  },
  skiing: {
    icon: require("../assets/images/icons/icon_skiing.png"),
    id: 22,
    type: "skiing",
    image: require("../assets/images/figures/skiing.png"),
    name: "Skiing",
  },
  videogame: {
    icon: require("../assets/images/icons/icon_videogame.png"),
    id: 18,
    type: "videogame",
    image: require("../assets/images/figures/videogame.png"),
    name: "Video Games",
  },
  volleyball: {
    icon: require("../assets/images/icons/icon_volleyball.png"),
    id: 17,
    type: "volleyball",
    image: require("../assets/images/figures/volleyball.png"),
    name: "Volleyball",
  },
  water_sports: {
    icon: require("../assets/images/icons/icon_water_sports.png"),
    id: 25,
    type: "water_sports",
    image: require("../assets/images/figures/water_sports.png"),
    name: "Water Sport",
  },
  weights: {
    icon: require("../assets/images/icons/icon_weightlifting.png"),
    id: 23,
    type: "weights",
    image: require("../assets/images/figures/weightlifting.png"),
    name: "Workout",
  },
  yoga: {
    icon: require("../assets/images/icons/icon_yoga.png"),
    id: 19,
    type: "yoga",
    image: require("../assets/images/figures/yoga.png"),
    name: "Yoga",
  },
  other: {
    icon: require("../assets/images/icons/icon_other.png"),
    id: 26,
    type: "other",
    image: require("../assets/images/figures/other.png"),
    name: "Other",
  },
};
