export const GET = "GET";
export const POST = "POST";
export const PUT = "PUT";
export const DELETE = "DELETE";
// export const URL = "https://api.ayupapp.com";
// export const URL = "https://api.ayupapp.com";
export const URL = "http://10.44.108.202:8080";
export const FBURL = "https://graph.facebook.com/v2.8/me/";
export const OPTLY_URL = "https://cdn.optimizely.com/json/8228072110.json";
